version: "3.8"
services:
  imgproxy:
    container_name: imgproxy
    image: darthsim/imgproxy:latest
    ports:
      - 8081:8080
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      timeout: 5s
      interval: 5s
      retries: 3
    volumes:
      - imgproxy_storage:/var/lib/storage:z

volumes:
  imgproxy_storage:

# Test 
# http://localhost:8081/insecure/rs:fill:300:400/g:sm/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL00v/TVY1Qk1tUTNabVk0/TnpZdFkyVm1ZaTAw/WkRSbUxUZ3lPREF0/WldZelpqaGxOemsx/TnpVMlhrRXlYa0Zx/Y0dkZVFYVnlOVGMz/TWpVek5USUAuanBn.jpg