version: '3.8'
services:
    flowise:
        image: flowiseai/flowise
        restart: always
        environment:
          - PORT=3000
          - DATABASE_PATH=/root/.flowise
          - APIKEY_PATH=/root/.flowise
          - SECRETKEY_PATH=/root/.flowise
          - LOG_PATH=/root/.flowise/logs
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
