version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://127.0.0.1:3000 # Replace with any existing APPlication API