version: '3.8'

services:
  onedev:
    image: 1dev/server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/onedev:/opt/onedev
    ports:
      - "6610:6610"
      - "6611:6611"
